on: [push, create]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${GITHUB_REF##*/}-${{ steps.slug.outputs.sha8 }}
          release_name: Release v${GITHUB_REF##*/}-${{ steps.slug.outputs.sha8 }}
          body: |
            Changes in this Release
            - A new change
            - A second new Change
            - Test 3
          draft: false
          prerelease: false
